version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: med
      MYSQL_USER: medapp
      MYSQL_PASSWORD: medapp
    volumes:
      - ./initial-up.sql:/docker-entrypoint-initdb.d/initial-up.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  app-network:
    driver: bridge